export const mdata = [
  {
    value: "year3",
    label: "3 év",
    items: [
      "lakóépület alapjai, fal- és födémszerkezetei",
      "lakások burkolatai (ideértve a festést, a mázolást, tapétázást is)",
      "lakóépület nyílászáró szerkezetei, korlátjai és mellvédjei",
      "lakóépület kéményei",
      "lakóépület tetőzete és az azon levő tetőfelépítmények",
      "lakóépületen levő ereszcsatornák és esővízlefolyó vezetékek",
      "lakóépület szigetelése és a külső vakolat",
      "főzőkészülék (tűzhely, főzőlap stb.)",
      "fűtőberendezés (egyedi kályha, konvektor, elektromos hőtároló kályha stb.)",
      "melegvízellátó berendezés (gáz-vízmelegítő, villanybojler, fürdőkályha)",
      "épületgépészeti és egészségügyi berendezések (falikút, mosogató, fürdőkád, zuhanyozó, mosdó, WC-tartály, WC-csésze stb. a hozzá tartozó szerelvényekkel)",
      "szellőztető berendezés (páraelszívó stb.)",
      "beépített bútor (beépített ruhásszekrény, konyhaszekrény stb.)",
      "redőny, vászonroló, napvédő függöny",
      "csengő és a kaputelefonnak a lakásban levő készüléke, valamint a kaputelefon és felcsengető berendezés a vezetékhálózattal",
      "lakás elektromos vezetékeihez tartozó kapcsolók és csatlakozóaljak",
      "központi fűtő- és melegvíz-szolgáltató berendezés a hozzá tartozó szerelvényekkel, ideértve a lakásban levő vezetékszakaszt és fűtőtesteket (radiátor stb.) is",
      "víz-, szennycsatorna- és gázvezeték a hozzá tartozó szerelvényekkel, ideértve a lakásban levő vezetékszakaszt is, a hozzá tartozó szerelvényekkel; gázvezeték esetén a közszolgáltató által jóváírással vagy üzemeltetésre átvett vezetékek és berendezési tárgyak kivételével",
      "elektromos vezeték és érintésvédelmi rendszere a lakásban levő vezetékszakaszt és szerelvényeket is ideértve, kivéve a közszolgáltató által jóváírással vagy üzemeltetésre átvett méretlen készüléket és fogyasztásmérőt",
      "lakást szolgáló szellőztető berendezés és a klímaberendezés",
      "központi antenna és erősítő berendezései, ideértve a lakásban levő vezetékszakaszt és csatlakozóaljat is",
      "személy- és teherfelvonó",
      "háztartásban keletkező hulladék gyűjtésére szolgáló berendezés",
      "lakást szolgáló kút a hozzá tartozó szerelvényekkel",
      "akásban keletkezett házi szennyvíznek a telekhatáron belüli elhelyezésére, illetőleg elszikkasztására szolgáló berendezés",
      "tetőterasz",
      "pince- és padlástérség vagy tüzelőtároló",
      "kapualj",
      "lépcsőház",
      "folyosók és függőfolyosók",
      "központi berendezések helyiségei",
      "mosókonyha",
      "szárítóhelyiség",
      "gyermekkocsi- és kerékpártároló helyiség",
      "gépkocsitároló helyiség (garázs, teremgarázs)",
      "hulladéktároló helyiség",
    ],
  },
  {
    value: "year5",
    label: "5 év",
    items: [
      "tetőhéjalások",
      "válaszfalak",
      "csapadékvíz és használati víz elleni szigetelés",
      "nyílászáró szerkezetek",
      "szerelt térelhatároló fal- és födémszerkezetek, álmennyezetek",
      "csapadékvíz elvezetés szerkezetei",
      "vakolatok, burkolatok, felületképzések (a mázolás, a belső falfestés, a meszelés és a tapétázás kivételével)",
      "szabadon vezetett épületgépészeti csővezetékek, berendezések",
      "klíma és szellőző berendezések",
      "elektromos tápvezetékek, jelző vezetékek, hálózatok",
      "villámvédelem",
      "felvonók",
    ],
  },
  {
    value: "year10",
    label: "10 év",
    items: [
      "teherbíróvá tett talajok",
      "alapozási szerkezetek",
      "teherhordó vázak",
      "födémek (burkolatok, álmennyezetek, bevilágítók nélkül: a szerelt födémszerkezetek kivételével)",
      "fedélszerkezetek (fedélhéjazat, hőszigetelés stb. nélkül)",
      "függőleges teherhordó- és térelhatároló szerkezetek (burkolatok, felületképzések, nyílászárók nélkül a szerelt külső térelhatároló falszerkezetek kivételével)",
      "szellőzőkürtők, kémények (béléselemek nélkül)",
      "talajvíz és talajnedvesség elleni szigetelések",
      "épületgépészeti csővezetékek, talajba kerülő (a szabadon vezetett épületgépészeti csővezetékek kivételével) vezetékek",
      "az építményhez szerkezetileg csatlakozó külső létesítmények",
    ],
  },
]
