import {
  AlertTriangle,
  ArrowRight,
  ArrowUpRight,
  ArrowsUpFromLine,
  BadgeCheck,
  Banknote,
  Blocks,
  BookCopy,
  BookOpen,
  BookOpenCheck,
  Bot,
  Calculator,
  CarFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronRightCircle,
  ChevronUp,
  Coins,
  Command,
  Copy,
  CreditCard,
  Facebook,
  File,
  FileText,
  Files,
  Flag,
  FolderDot,
  Group,
  HelpCircle,
  Home,
  Hourglass,
  Image,
  Landmark,
  Laptop,
  Leaf,
  Link,
  Link2,
  Linkedin,
  List,
  ListTodo,
  ListTree,
  Loader2,
  XIcon as LucideIcon,
  Mail,
  MapPin,
  MessageSquareDashed,
  MessageSquarePlus,
  Moon,
  MoreVertical,
  PenLine,
  Phone,
  PiggyBank,
  Pizza,
  Plus,
  Radio,
  Scale,
  ScrollText,
  Settings,
  SmartphoneNfc,
  Sparkles,
  Stamp,
  Star,
  SunMedium,
  Tag,
  TextSelect,
  Timer,
  Trash,
  Trophy,
  Twitter,
  User,
  Users,
  Wallet,
  XIcon,
  Newspaper,
  Search,
  Workflow
} from "lucide-react"

export type Icon = typeof LucideIcon

export const Icons = {
  logo: Command,
  copy: Copy,
  workflow: Workflow,
  search: Search,
  close: XIcon,
  car: CarFront,
  newspaper: Newspaper,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  trash: Trash,
  post: FileText,
  scrollText: ScrollText,
  page: File,
  landmark: Landmark,
  home: Home,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  contact: PenLine,
  message: MessageSquarePlus,
  messageDashed: MessageSquareDashed,
  calculator: Calculator,
  files: Files,
  book: BookOpenCheck,
  blocks: Blocks,
  listTree: ListTree,
  radio: Radio,
  mapPin: MapPin,
  stamp: Stamp,
  piggyBank: PiggyBank,
  coins: Coins,
  banknote: Banknote,
  wallet: Wallet,
  folderDot: FolderDot,
  listTodo: ListTodo,
  smartphoneNFC: SmartphoneNfc,
  moreCircle: ChevronRightCircle,
  phone: Phone,
  trophy: Trophy,
  facebook: Facebook,
  mail: Mail,
  linkedin: Linkedin,
  reddit: Bot,
  blog: TextSelect,
  list: List,
  arrowsUp: ArrowsUpFromLine,
  leaf: Leaf,
  sparkles: Sparkles,
  hourglass: Hourglass,
  timer: Timer,
  group: Group,
  flag: Flag,
  star: Star,
  scale: Scale,
  bookOpen: BookOpen,
  arrowUpRight: ArrowUpRight,
  badgeCheck: BadgeCheck,
  bookCopy: BookCopy,
  link: Link,
  link2: Link2,
  users: Users,
  tag: Tag,
}
